### ISSUE TITLE
Mandy needs Twizzlers

### ISSUE THREAD

**Issue by MandyRawls** [MozillaFoundation/playground#3]
Red only

**Comment by simonwex** [comment]
@Michaelaukland do you think she means the turkey things?

**Comment by Michaelaukland** [comment]
No, she means the candy.

**Comment by simonwex** [comment]
@MandyRawls not a fan of real liquorice, no?

**Comment by simonwex** [comment]
This looks like something I can do!

**Comment by simonwex** [comment]
I bought these:

![image](https://cloud.githubusercontent.com/assets/25260/13262373/580a86f0-da19-11e5-9436-bde3e3548a19.png)
